name: Manual File Upload and Excel Update

on:
  workflow_dispatch:
    inputs:
      excel_file:
        description: 'Upload Excel file (CARMOTION_GOMMAS.xlsx)'
        required: true

jobs:
  upload_and_process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Excel File
        run: |
          echo "Subiendo archivo proporcionado..."
          echo "${{ github.event.inputs.excel_file }}" > CARMOTION_GOMMAS.xlsx

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pandas openpyxl requests

      - name: Run Python Script
        run: |
          python script.py

      - name: Save Updated Excel File as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CARMOTION_GOMMAS_ACTUALIZADO
          path: CARMOTION_GOMMAS_ACTUALIZADO.xlsx
